<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();
$arComponentParameters = array(
	"GROUPS" => array(
		"SETTINGS" => array(
			"NAME" => GetMessage("T_IBLOCK_DESC_SETTINGS"),
			"SORT" => 100,
		),
		"PRICE" => array(
			"NAME" => GetMessage("T_IBLOCK_DESC_PRICE"),
			"SORT" => 200,
		),
		"GALLERY" => array(
			"NAME" => GetMessage("T_IBLOCK_DESC_GALLERY"),
			"SORT" => 300,
		),
	),
	"PARAMETERS" => array(
		"IBLOCK_TYPE" => array(
			"PARENT" => "BASE",
			"NAME" => GetMessage("T_IBLOCK_DESC_TYPE"),
			"TYPE" => "LIST",
			"VALUES" => $arIBLockType,
			"REFRESH" => "Y",
		),
		"IBLOCK_ID" => array(
			"PARENT" => "BASE",
			"NAME" => GetMessage("T_IBLOCK_DESC_ID"),
			"TYPE" => "LIST",
			"VALUES" => $arIBlock,
			"REFRESH" => "Y",
			"ADDITIONAL_VALUES" => "Y",
		),
		"SECTION_SORT_FIELD" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_SECTION_SORT_FIELD"),
			"TYPE" => "LIST",
			"VALUES" => array(
				"sort" => GetMessage("T_IBLOCK_DESC_SECTION_SORT_FIELD_SORT"),
				"id" => GetMessage("T_IBLOCK_DESC_SECTION_SORT_FIELD_ID"),
				"name" => GetMessage("T_IBLOCK_DESC_SECTION_SORT_FIELD_NAME"),
			),
			"DEFAULT" => "sort",
		),
		"SECTION_SORT_ORDER" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_SECTION_SORT_ORDER"),
			"TYPE" => "LIST",
			"VALUES" => array(
				"asc" => GetMessage("T_IBLOCK_DESC_SECTION_SORT_ORDER_ASC"),
				"desc" => GetMessage("T_IBLOCK_DESC_SECTION_SORT_ORDER_DESC"),
			),
			"DEFAULT" => "asc",
		),
		"ELEMENT_SORT_FIELD" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD"),
			"TYPE" => "LIST",
			"VALUES" => array(
				"sort" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_SORT"),
				"id" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_ID"),
				"name" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_NAME"),
				"date_active_from" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_DATE_ACTIVE_FROM"),
			),
			"DEFAULT" => "sort",
		),
		"ELEMENT_SORT_ORDER" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_ORDER"),
			"TYPE" => "LIST",
			"VALUES" => array(
				"asc" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_ORDER_ASC"),
				"desc" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_ORDER_DESC"),
			),
			"DEFAULT" => "asc",
		),
		"ELEMENT_SORT_FIELD2" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD2"),
			"TYPE" => "LIST",
			"VALUES" => array(
				"sort" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_SORT"),
				"id" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_ID"),
				"name" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_NAME"),
				"date_active_from" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_DATE_ACTIVE_FROM"),
			),
			"DEFAULT" => "id",
		),
		"ELEMENT_SORT_ORDER2" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_ORDER2"),
			"TYPE" => "LIST",
			"VALUES" => array(
				"asc" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_ORDER_ASC"),
				"desc" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_ORDER_DESC"),
			),
			"DEFAULT" => "desc",
		),
		"PROPERTY_CODE" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_PROPERTY_CODE"),
			"TYPE" => "LIST",
			"MULTIPLE" => "Y",
			"VALUES" => $arProperty,
			"ADDITIONAL_VALUES" => "Y",
		),
		"OFFERS_FIELD_CODE" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_OFFERS_FIELD_CODE"),
			"TYPE" => "LIST",
			"MULTIPLE" => "Y",
			"VALUES" => $arProperty,
			"ADDITIONAL_VALUES" => "Y",
		),
		"OFFERS_PROPERTY_CODE" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_OFFERS_PROPERTY_CODE"),
			"TYPE" => "LIST",
			"MULTIPLE" => "Y",
			"VALUES" => $arProperty,
			"ADDITIONAL_VALUES" => "Y",
		),
		"OFFERS_LIMIT" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_OFFERS_LIMIT"),
			"TYPE" => "STRING",
			"DEFAULT" => "5",
		),
		"PRICE_CODE" => array(
			"PARENT" => "PRICE",
			"NAME" => GetMessage("T_IBLOCK_DESC_PRICE_CODE"),
			"TYPE" => "LIST",
			"MULTIPLE" => "Y",
			"VALUES" => $arPrice,
		),
		"USE_PRICE_COUNT" => array(
			"PARENT" => "PRICE",
			"NAME" => GetMessage("T_IBLOCK_DESC_USE_PRICE_COUNT"),
			"TYPE" => "CHECKBOX",
			"DEFAULT" => "N",
		),
		"SHOW_PRICE_COUNT" => array(
			"PARENT" => "PRICE",
			"NAME" => GetMessage("T_IBLOCK_DESC_SHOW_PRICE_COUNT"),
			"TYPE" => "STRING",
			"DEFAULT" => "1",
		),
		"PRICE_VAT_INCLUDE" => array(
			"PARENT" => "PRICE",
			"NAME" => GetMessage("T_IBLOCK_DESC_PRICE_VAT_INCLUDE"),
			"TYPE" => "CHECKBOX",
			"DEFAULT" => "Y",
		),
		"CONVERT_CURRENCY" => array(
			"PARENT" => "PRICE",
			"NAME" => GetMessage("T_IBLOCK_DESC_CONVERT_CURRENCY"),
			"TYPE" => "CHECKBOX",
			"DEFAULT" => "N",
		),
		"CURRENCY_ID" => array(
			"PARENT" => "PRICE",
			"NAME" => GetMessage("T_IBLOCK_DESC_CURRENCY_ID"),
			"TYPE" => "LIST",
			"VALUES" => $arCurrency,
			"DEFAULT" => "RUB",
			"ADDITIONAL_VALUES" => "Y",
		),
		"USE_ELEMENT_COUNTER" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_USE_ELEMENT_COUNTER"),
			"TYPE" => "CHECKBOX",
			"DEFAULT" => "Y",
		),
		"SHOW_DEACTIVATED" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_SHOW_DEACTIVATED"),
			"TYPE" => "CHECKBOX",
			"DEFAULT" => "N",
		),
		"DISPLAY_COMPARE" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_DISPLAY_COMPARE"),
			"TYPE" => "CHECKBOX",
			"DEFAULT" => "N",
		),
		"COMPARE_PATH" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_COMPARE_PATH"),
			"TYPE" => "STRING",
			"DEFAULT" => "/catalog/compare.php",
		),
		"USE_REGION" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_USE_REGION"),
			"TYPE" => "CHECKBOX",
			"DEFAULT" => "N",
		),
		"SHOW_GALLERY" => array(
			"PARENT" => "GALLERY",
			"NAME" => GetMessage("T_IBLOCK_DESC_SHOW_GALLERY"),
			"TYPE" => "CHECKBOX",
			"DEFAULT" => "Y",
		),
		"GALLERY_THUMB_SIZE" => array(
			"PARENT" => "GALLERY",
			"NAME" => GetMessage("T_IBLOCK_DESC_GALLERY_THUMB_SIZE"),
			"TYPE" => "STRING",
			"DEFAULT" => "100",
		),
		"GALLERY_MAIN_SIZE" => array(
			"PARENT" => "GALLERY",
			"NAME" => GetMessage("T_IBLOCK_DESC_GALLERY_MAIN_SIZE"),
			"TYPE" => "STRING",
			"DEFAULT" => "600",
		),
		"CACHE_TYPE" => array(
			"PARENT" => "CACHE_SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_CACHE_TYPE"),
			"TYPE" => "LIST",
			"VALUES" => array(
				"A" => GetMessage("T_IBLOCK_DESC_CACHE_TYPE_AUTO"),
				"Y" => GetMessage("T_IBLOCK_DESC_CACHE_TYPE_YES"),
				"N" => GetMessage("T_IBLOCK_DESC_CACHE_TYPE_NO"),
			),
			"DEFAULT" => "A",
		),
		"CACHE_TIME" => array(
			"PARENT" => "CACHE_SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_CACHE_TIME"),
			"TYPE" => "STRING",
			"DEFAULT" => "36000000",
		),
		"CACHE_GROUPS" => array(
			"PARENT" => "CACHE_SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_CACHE_GROUPS"),
			"TYPE" => "CHECKBOX",
			"DEFAULT" => "Y",
		),
	),
);
?> 