<? if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true) die();
$arComponentParameters = [
  "GROUPS" => [
    "SETTINGS" => [
      "NAME" => GetMessage("T_IBLOCK_DESC_SETTINGS"),
      "SORT" => 100,
    ],
    "PRICE" => [
      "NAME" => GetMessage("T_IBLOCK_DESC_PRICE"),
      "SORT" => 200,
    ],
    "FILTER" => [
      "NAME" => GetMessage("T_IBLOCK_DESC_FILTER"),
      "SORT" => 300,
    ],
  ],
  "PARAMETERS" => [
    "IBLOCK_TYPE" => [
      "PARENT" => "BASE",
      "NAME" => GetMessage("T_IBLOCK_DESC_TYPE"),
      "TYPE" => "LIST",
      "VALUES" => $arIBLockType,
      "REFRESH" => "Y",
    ],
    "IBLOCK_ID" => [
      "PARENT" => "BASE",
      "NAME" => GetMessage("T_IBLOCK_DESC_ID"),
      "TYPE" => "LIST",
      "VALUES" => $arIBlock,
      "REFRESH" => "Y",
      "ADDITIONAL_VALUES" => "Y",
    ],
    "SECTION_ID" => [
      "PARENT" => "BASE",
      "NAME" => GetMessage("T_IBLOCK_DESC_SECTION_ID"),
      "TYPE" => "STRING",
      "DEFAULT" => '={$_REQUEST["SECTION_ID"]}',
    ],
    "SECTION_CODE" => [
      "PARENT" => "BASE",
      "NAME" => GetMessage("T_IBLOCK_DESC_SECTION_CODE"),
      "TYPE" => "STRING",
      "DEFAULT" => '',
    ],
    "SECTION_CODE_PATH" => [
      "PARENT" => "BASE",
      "NAME" => GetMessage("T_IBLOCK_DESC_SECTION_CODE_PATH"),
      "TYPE" => "STRING",
      "DEFAULT" => '',
    ],
    "ELEMENT_SORT_FIELD" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD"),
      "TYPE" => "LIST",
      "VALUES" => [
        "sort" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_SORT"),
        "name" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_NAME"),
        "id" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_ID"),
        "date" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_DATE"),
        "price" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_PRICE"),
      ],
      "DEFAULT" => "sort",
      "ADDITIONAL_VALUES" => "Y",
    ],
    "ELEMENT_SORT_ORDER" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_ORDER"),
      "TYPE" => "LIST",
      "VALUES" => [
        "asc" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_ORDER_ASC"),
        "desc" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_ORDER_DESC"),
      ],
      "DEFAULT" => "asc",
    ],
    "ELEMENT_SORT_FIELD2" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD2"),
      "TYPE" => "LIST",
      "VALUES" => [
        "id" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_ID"),
        "name" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_NAME"),
        "sort" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_SORT"),
        "date" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_DATE"),
        "price" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_PRICE"),
      ],
      "DEFAULT" => "id",
      "ADDITIONAL_VALUES" => "Y",
    ],
    "ELEMENT_SORT_ORDER2" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_ORDER2"),
      "TYPE" => "LIST",
      "VALUES" => [
        "asc" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_ORDER_ASC"),
        "desc" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_ORDER_DESC"),
      ],
      "DEFAULT" => "desc",
    ],
    "ELEMENT_COUNT" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_ELEMENT_COUNT"),
      "TYPE" => "STRING",
      "DEFAULT" => "20",
    ],
    "LINE_ELEMENT_COUNT" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_LINE_ELEMENT_COUNT"),
      "TYPE" => "STRING",
      "DEFAULT" => "3",
    ],
    "PROPERTY_CODE" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_PROPERTY_CODE"),
      "TYPE" => "LIST",
      "MULTIPLE" => "Y",
      "VALUES" => $arProperty_LNS,
      "ADDITIONAL_VALUES" => "Y",
    ],
    "OFFERS_FIELD_CODE" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_OFFERS_FIELD_CODE"),
      "TYPE" => "LIST",
      "MULTIPLE" => "Y",
      "VALUES" => $arProperty_Off,
      "ADDITIONAL_VALUES" => "Y",
    ],
    "OFFERS_PROPERTY_CODE" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_OFFERS_PROPERTY_CODE"),
      "TYPE" => "LIST",
      "MULTIPLE" => "Y",
      "VALUES" => $arProperty_Off,
      "ADDITIONAL_VALUES" => "Y",
    ],
    "OFFERS_SORT_FIELD" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_OFFERS_SORT_FIELD"),
      "TYPE" => "LIST",
      "VALUES" => [
        "id" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_ID"),
        "name" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_NAME"),
        "sort" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_SORT"),
        "price" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_PRICE"),
      ],
      "DEFAULT" => "sort",
      "ADDITIONAL_VALUES" => "Y",
    ],
    "OFFERS_SORT_ORDER" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_OFFERS_SORT_ORDER"),
      "TYPE" => "LIST",
      "VALUES" => [
        "asc" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_ORDER_ASC"),
        "desc" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_ORDER_DESC"),
      ],
      "DEFAULT" => "asc",
    ],
    "OFFERS_SORT_FIELD2" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_OFFERS_SORT_FIELD2"),
      "TYPE" => "LIST",
      "VALUES" => [
        "id" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_ID"),
        "name" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_NAME"),
        "sort" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_SORT"),
        "price" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_PRICE"),
      ],
      "DEFAULT" => "id",
      "ADDITIONAL_VALUES" => "Y",
    ],
    "OFFERS_SORT_ORDER2" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_OFFERS_SORT_ORDER2"),
      "TYPE" => "LIST",
      "VALUES" => [
        "asc" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_ORDER_ASC"),
        "desc" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_ORDER_DESC"),
      ],
      "DEFAULT" => "desc",
    ],
    "OFFERS_LIMIT" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_OFFERS_LIMIT"),
      "TYPE" => "STRING",
      "DEFAULT" => "5",
    ],
    "SECTION_URL" => [
      "PARENT" => "URL_TEMPLATES",
      "NAME" => GetMessage("T_IBLOCK_DESC_SECTION_URL"),
      "TYPE" => "STRING",
      "DEFAULT" => "",
    ],
    "CACHE_TYPE" => [
      "PARENT" => "CACHE_SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_CACHE_TYPE"),
      "TYPE" => "LIST",
      "VALUES" => [
        "A" => GetMessage("T_IBLOCK_DESC_CACHE_TYPE_AUTO"),
        "Y" => GetMessage("T_IBLOCK_DESC_CACHE_TYPE_YES"),
        "N" => GetMessage("T_IBLOCK_DESC_CACHE_TYPE_NO"),
      ],
      "DEFAULT" => "A",
    ],
    "CACHE_TIME" => [
      "PARENT" => "CACHE_SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_CACHE_TIME"),
      "TYPE" => "STRING",
      "DEFAULT" => "36000000",
    ],
    "CACHE_GROUPS" => [
      "PARENT" => "CACHE_SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_CACHE_GROUPS"),
      "TYPE" => "CHECKBOX",
      "DEFAULT" => "Y",
    ],
    "DISPLAY_COMPARE" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_DISPLAY_COMPARE"),
      "TYPE" => "CHECKBOX",
      "DEFAULT" => "N",
    ],
    "COMPARE_PATH" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_COMPARE_PATH"),
      "TYPE" => "STRING",
      "DEFAULT" => "",
    ],
    "PRICE_CODE" => [
      "PARENT" => "PRICE",
      "NAME" => GetMessage("T_IBLOCK_DESC_PRICE_CODE"),
      "TYPE" => "LIST",
      "MULTIPLE" => "Y",
      "VALUES" => $arPrice,
    ],
    "USE_PRICE_COUNT" => [
      "PARENT" => "PRICE",
      "NAME" => GetMessage("T_IBLOCK_DESC_USE_PRICE_COUNT"),
      "TYPE" => "CHECKBOX",
      "DEFAULT" => "N",
    ],
    "SHOW_PRICE_COUNT" => [
      "PARENT" => "PRICE",
      "NAME" => GetMessage("T_IBLOCK_DESC_SHOW_PRICE_COUNT"),
      "TYPE" => "STRING",
      "DEFAULT" => "1",
    ],
    "PRICE_VAT_INCLUDE" => [
      "PARENT" => "PRICE",
      "NAME" => GetMessage("T_IBLOCK_DESC_PRICE_VAT_INCLUDE"),
      "TYPE" => "CHECKBOX",
      "DEFAULT" => "Y",
    ],
    "CONVERT_CURRENCY" => [
      "PARENT" => "PRICE",
      "NAME" => GetMessage("T_IBLOCK_DESC_CONVERT_CURRENCY"),
      "TYPE" => "CHECKBOX",
      "DEFAULT" => "N",
    ],
    "CURRENCY_ID" => [
      "PARENT" => "PRICE",
      "NAME" => GetMessage("T_IBLOCK_DESC_CURRENCY_ID"),
      "TYPE" => "LIST",
      "VALUES" => $arCurrency,
      "DEFAULT" => "USD",
    ],
    "HIDE_NOT_AVAILABLE" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_HIDE_NOT_AVAILABLE"),
      "TYPE" => "CHECKBOX",
      "DEFAULT" => "N",
    ],
    "HIDE_NOT_AVAILABLE_OFFERS" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_HIDE_NOT_AVAILABLE_OFFERS"),
      "TYPE" => "CHECKBOX",
      "DEFAULT" => "N",
    ],
    "USE_FILTER" => [
      "PARENT" => "FILTER",
      "NAME" => GetMessage("T_IBLOCK_DESC_USE_FILTER"),
      "TYPE" => "CHECKBOX",
      "DEFAULT" => "N",
      "REFRESH" => "Y",
    ],
  ],
];
if ($arCurrentValues["USE_FILTER"] == "Y") {
  $arComponentParameters["PARAMETERS"]["FILTER_NAME"] = [
    "PARENT" => "FILTER",
    "NAME" => GetMessage("T_IBLOCK_DESC_FILTER_NAME"),
    "TYPE" => "STRING",
    "DEFAULT" => "arrFilter",
  ];
  $arComponentParameters["PARAMETERS"]["FILTER_FIELD_CODE"] = [
    "PARENT" => "FILTER",
    "NAME" => GetMessage("T_IBLOCK_DESC_FILTER_FIELD_CODE"),
    "TYPE" => "LIST",
    "MULTIPLE" => "Y",
    "VALUES" => $arProperty_LNS,
    "ADDITIONAL_VALUES" => "Y",
  ];
  $arComponentParameters["PARAMETERS"]["FILTER_PROPERTY_CODE"] = [
    "PARENT" => "FILTER",
    "NAME" => GetMessage("T_IBLOCK_DESC_FILTER_PROPERTY_CODE"),
    "TYPE" => "LIST",
    "MULTIPLE" => "Y",
    "VALUES" => $arProperty_LNS,
    "ADDITIONAL_VALUES" => "Y",
  ];
}
?>
