<? if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true) die();
$arComponentParameters = [
  "GROUPS" => [
    "SETTINGS" => [
      "NAME" => GetMessage("T_IBLOCK_DESC_SETTINGS"),
      "SORT" => 100,
    ],
    "PRICE" => [
      "NAME" => GetMessage("T_IBLOCK_DESC_PRICE"),
      "SORT" => 200,
    ],
    "GALLERY" => [
      "NAME" => GetMessage("T_IBLOCK_DESC_GALLERY"),
      "SORT" => 300,
    ],
  ],
  "PARAMETERS" => [
    "IBLOCK_TYPE" => [
      "PARENT" => "BASE",
      "NAME" => GetMessage("T_IBLOCK_DESC_TYPE"),
      "TYPE" => "LIST",
      "VALUES" => $arIBLockType,
      "REFRESH" => "Y",
    ],
    "IBLOCK_ID" => [
      "PARENT" => "BASE",
      "NAME" => GetMessage("T_IBLOCK_DESC_ID"),
      "TYPE" => "LIST",
      "VALUES" => $arIBlock,
      "REFRESH" => "Y",
      "ADDITIONAL_VALUES" => "Y",
    ],
    "ELEMENT_ID" => [
      "PARENT" => "BASE",
      "NAME" => GetMessage("T_IBLOCK_DESC_ELEMENT_ID"),
      "TYPE" => "STRING",
      "DEFAULT" => "={$_REQUEST['ELEMENT_ID']}",
    ],
    "ELEMENT_CODE" => [
      "PARENT" => "BASE",
      "NAME" => GetMessage("T_IBLOCK_DESC_ELEMENT_CODE"),
      "TYPE" => "STRING",
      "DEFAULT" => "={$_REQUEST['ELEMENT_CODE']}",
    ],
    "PROPERTY_CODE" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_PROPERTY_CODE"),
      "TYPE" => "LIST",
      "MULTIPLE" => "Y",
      "VALUES" => $arProperty,
      "ADDITIONAL_VALUES" => "Y",
    ],
    "OFFERS_FIELD_CODE" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_OFFERS_FIELD_CODE"),
      "TYPE" => "LIST",
      "MULTIPLE" => "Y",
      "VALUES" => $arProperty,
      "ADDITIONAL_VALUES" => "Y",
    ],
    "OFFERS_PROPERTY_CODE" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_OFFERS_PROPERTY_CODE"),
      "TYPE" => "LIST",
      "MULTIPLE" => "Y",
      "VALUES" => $arProperty,
      "ADDITIONAL_VALUES" => "Y",
    ],
    "OFFERS_LIMIT" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_OFFERS_LIMIT"),
      "TYPE" => "STRING",
      "DEFAULT" => "5",
    ],
    "PRICE_CODE" => [
      "PARENT" => "PRICE",
      "NAME" => GetMessage("T_IBLOCK_DESC_PRICE_CODE"),
      "TYPE" => "LIST",
      "MULTIPLE" => "Y",
      "VALUES" => $arPrice,
    ],
    "USE_PRICE_COUNT" => [
      "PARENT" => "PRICE",
      "NAME" => GetMessage("T_IBLOCK_DESC_USE_PRICE_COUNT"),
      "TYPE" => "CHECKBOX",
      "DEFAULT" => "N",
    ],
    "SHOW_PRICE_COUNT" => [
      "PARENT" => "PRICE",
      "NAME" => GetMessage("T_IBLOCK_DESC_SHOW_PRICE_COUNT"),
      "TYPE" => "STRING",
      "DEFAULT" => "1",
    ],
    "PRICE_VAT_INCLUDE" => [
      "PARENT" => "PRICE",
      "NAME" => GetMessage("T_IBLOCK_DESC_PRICE_VAT_INCLUDE"),
      "TYPE" => "CHECKBOX",
      "DEFAULT" => "Y",
    ],
    "CONVERT_CURRENCY" => [
      "PARENT" => "PRICE",
      "NAME" => GetMessage("T_IBLOCK_DESC_CONVERT_CURRENCY"),
      "TYPE" => "CHECKBOX",
      "DEFAULT" => "N",
    ],
    "CURRENCY_ID" => [
      "PARENT" => "PRICE",
      "NAME" => GetMessage("T_IBLOCK_DESC_CURRENCY_ID"),
      "TYPE" => "LIST",
      "VALUES" => $arCurrency,
      "DEFAULT" => "USD",
      "ADDITIONAL_VALUES" => "Y",
    ],
    "USE_ELEMENT_COUNTER" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_USE_ELEMENT_COUNTER"),
      "TYPE" => "CHECKBOX",
      "DEFAULT" => "Y",
    ],
    "SHOW_DEACTIVATED" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_SHOW_DEACTIVATED"),
      "TYPE" => "CHECKBOX",
      "DEFAULT" => "N",
    ],
    "SHOW_404" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_SHOW_404"),
      "TYPE" => "CHECKBOX",
      "DEFAULT" => "Y",
    ],
    "MESSAGE_404" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_MESSAGE_404"),
      "TYPE" => "STRING",
      "DEFAULT" => GetMessage("T_IBLOCK_DESC_MESSAGE_404_DEFAULT"),
    ],
    "DISPLAY_COMPARE" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_DISPLAY_COMPARE"),
      "TYPE" => "CHECKBOX",
      "DEFAULT" => "N",
    ],
    "COMPARE_PATH" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_COMPARE_PATH"),
      "TYPE" => "STRING",
      "DEFAULT" => "/catalog/compare.php",
    ],
    "USE_REGION" => [
      "PARENT" => "SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_USE_REGION"),
      "TYPE" => "CHECKBOX",
      "DEFAULT" => "N",
    ],
    "SHOW_GALLERY" => [
      "PARENT" => "GALLERY",
      "NAME" => GetMessage("T_IBLOCK_DESC_SHOW_GALLERY"),
      "TYPE" => "CHECKBOX",
      "DEFAULT" => "Y",
    ],
    "GALLERY_THUMB_SIZE" => [
      "PARENT" => "GALLERY",
      "NAME" => GetMessage("T_IBLOCK_DESC_GALLERY_THUMB_SIZE"),
      "TYPE" => "STRING",
      "DEFAULT" => "100",
    ],
    "GALLERY_MAIN_SIZE" => [
      "PARENT" => "GALLERY",
      "NAME" => GetMessage("T_IBLOCK_DESC_GALLERY_MAIN_SIZE"),
      "TYPE" => "STRING",
      "DEFAULT" => "600",
    ],
    "CACHE_TYPE" => [
      "PARENT" => "CACHE_SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_CACHE_TYPE"),
      "TYPE" => "LIST",
      "VALUES" => [
        "A" => GetMessage("T_IBLOCK_DESC_CACHE_TYPE_AUTO"),
        "Y" => GetMessage("T_IBLOCK_DESC_CACHE_TYPE_YES"),
        "N" => GetMessage("T_IBLOCK_DESC_CACHE_TYPE_NO"),
      ],
      "DEFAULT" => "A",
    ],
    "CACHE_TIME" => [
      "PARENT" => "CACHE_SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_CACHE_TIME"),
      "TYPE" => "STRING",
      "DEFAULT" => "36000000",
    ],
    "CACHE_GROUPS" => [
      "PARENT" => "CACHE_SETTINGS",
      "NAME" => GetMessage("T_IBLOCK_DESC_CACHE_GROUPS"),
      "TYPE" => "CHECKBOX",
      "DEFAULT" => "Y",
    ],
  ],
];
?>
