<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();
$arTemplateParameters = array(
    "DISPLAY_COMPARE" => Array(
        "NAME" => GetMessage("T_IBLOCK_DESC_NEWS_COMPARE"),
        "TYPE" => "CHECKBOX",
        "MULTIPLE" => "N",
        "VALUE" => "Y",
        "DEFAULT" => "N",
    ),
    "COMPARE_PATH" => array(
        "NAME" => GetMessage("T_IBLOCK_DESC_NEWS_COMPARE_PATH"),
        "TYPE" => "STRING",
        "DEFAULT" => "/catalog/compare.php",
    ),
    "SHOW_DISCOUNT_PERCENT" => Array(
        "NAME" => GetMessage("CPSL_SHOW_DISCOUNT_PERCENT"),
        "TYPE" => "CHECKBOX",
        "MULTIPLE" => "N",
        "VALUE" => "Y",
        "DEFAULT" => "Y",
    ),
    "SHOW_OLD_PRICE" => Array(
        "NAME" => GetMessage("CPSL_SHOW_OLD_PRICE"),
        "TYPE" => "CHECKBOX",
        "MULTIPLE" => "N",
        "VALUE" => "Y",
        "DEFAULT" => "Y",
    ),
    "SHOW_RATING" => Array(
        "NAME" => GetMessage("CPSL_SHOW_RATING"),
        "TYPE" => "CHECKBOX",
        "MULTIPLE" => "N",
        "VALUE" => "Y",
        "DEFAULT" => "Y",
    ),
    "SHOW_DISCOUNT_TIME" => Array(
        "NAME" => GetMessage("CPSL_SHOW_DISCOUNT_TIME"),
        "TYPE" => "CHECKBOX",
        "MULTIPLE" => "N",
        "VALUE" => "Y",
        "DEFAULT" => "Y",
    ),
    "SHOW_DISCOUNT_PERCENT_NUMBER" => Array(
        "NAME" => GetMessage("CPSL_SHOW_DISCOUNT_PERCENT_NUMBER"),
        "TYPE" => "CHECKBOX",
        "MULTIPLE" => "N",
        "VALUE" => "Y",
        "DEFAULT" => "Y",
    ),
    "SHOW_DISCOUNT_SAVE" => Array(
        "NAME" => GetMessage("CPSL_SHOW_DISCOUNT_SAVE"),
        "TYPE" => "CHECKBOX",
        "MULTIPLE" => "N",
        "VALUE" => "Y",
        "DEFAULT" => "Y",
    ),
    "SHOW_DISCOUNT_NAME" => Array(
        "NAME" => GetMessage("CPSL_SHOW_DISCOUNT_NAME"),
        "TYPE" => "CHECKBOX",
        "MULTIPLE" => "N",
        "VALUE" => "Y",
        "DEFAULT" => "Y",
    ),
    "SHOW_DISCOUNT_PERCENT_VALUES" => Array(
        "NAME" => GetMessage("CPSL_SHOW_DISCOUNT_PERCENT_VALUES"),
        "TYPE" => "CHECKBOX",
        "MULTIPLE" => "N",
        "VALUE" => "Y",
        "DEFAULT" => "Y",
    ),
    "SHOW_DISCOUNT_PERCENT_NUMBER_OLD" => Array(
        "NAME" => GetMessage("CPSL_SHOW_DISCOUNT_PERCENT_NUMBER_OLD"),
        "TYPE" => "CHECKBOX",
        "MULTIPLE" => "N",
        "VALUE" => "Y",
        "DEFAULT" => "Y",
    ),
    "SHOW_DISCOUNT_PERCENT_NUMBER_NEW" => Array(
        "NAME" => GetMessage("CPSL_SHOW_DISCOUNT_PERCENT_NUMBER_NEW"),
        "TYPE" => "CHECKBOX",
        "MULTIPLE" => "N",
        "VALUE" => "Y",
        "DEFAULT" => "Y",
    ),
    "SHOW_DISCOUNT_PERCENT_NUMBER_OLD_ABS" => Array(
        "NAME" => GetMessage("CPSL_SHOW_DISCOUNT_PERCENT_NUMBER_OLD_ABS"),
        "TYPE" => "CHECKBOX",
        "MULTIPLE" => "N",
        "VALUE" => "Y",
        "DEFAULT" => "Y",
    ),
    "SHOW_DISCOUNT_PERCENT_NUMBER_NEW_ABS" => Array(
        "NAME" => GetMessage("CPSL_SHOW_DISCOUNT_PERCENT_NUMBER_NEW_ABS"),
        "TYPE" => "CHECKBOX",
        "MULTIPLE" => "N",
        "VALUE" => "Y",
        "DEFAULT" => "Y",
    ),
);
?> 