<? if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true) die();
$arTemplateParameters = [
  "DISPLAY_COMPARE" => [
    "NAME" => GetMessage("T_IBLOCK_DESC_NEWS_COMPARE"),
    "TYPE" => "CHECKBOX",
    "MULTIPLE" => "N",
    "VALUE" => "Y",
    "DEFAULT" => "N",
  ],
  "COMPARE_PATH" => [
    "NAME" => GetMessage("T_IBLOCK_DESC_NEWS_COMPARE_PATH"),
    "TYPE" => "STRING",
    "DEFAULT" => "/catalog/compare.php",
  ],
  "SHOW_DISCOUNT_PERCENT" => [
    "NAME" => GetMessage("CPSL_SHOW_DISCOUNT_PERCENT"),
    "TYPE" => "CHECKBOX",
    "MULTIPLE" => "N",
    "VALUE" => "Y",
    "DEFAULT" => "Y",
  ],
  "SHOW_OLD_PRICE" => [
    "NAME" => GetMessage("CPSL_SHOW_OLD_PRICE"),
    "TYPE" => "CHECKBOX",
    "MULTIPLE" => "N",
    "VALUE" => "Y",
    "DEFAULT" => "Y",
  ],
  "SHOW_RATING" => [
    "NAME" => GetMessage("CPSL_SHOW_RATING"),
    "TYPE" => "CHECKBOX",
    "MULTIPLE" => "N",
    "VALUE" => "Y",
    "DEFAULT" => "Y",
  ],
  "SHOW_DISCOUNT_TIME" => [
    "NAME" => GetMessage("CPSL_SHOW_DISCOUNT_TIME"),
    "TYPE" => "CHECKBOX",
    "MULTIPLE" => "N",
    "VALUE" => "Y",
    "DEFAULT" => "Y",
  ],
  "SHOW_DISCOUNT_PERCENT_NUMBER" => [
    "NAME" => GetMessage("CPSL_SHOW_DISCOUNT_PERCENT_NUMBER"),
    "TYPE" => "CHECKBOX",
    "MULTIPLE" => "N",
    "VALUE" => "Y",
    "DEFAULT" => "Y",
  ],
  "SHOW_DISCOUNT_SAVE" => [
    "NAME" => GetMessage("CPSL_SHOW_DISCOUNT_SAVE"),
    "TYPE" => "CHECKBOX",
    "MULTIPLE" => "N",
    "VALUE" => "Y",
    "DEFAULT" => "Y",
  ],
  "SHOW_DISCOUNT_NAME" => [
    "NAME" => GetMessage("CPSL_SHOW_DISCOUNT_NAME"),
    "TYPE" => "CHECKBOX",
    "MULTIPLE" => "N",
    "VALUE" => "Y",
    "DEFAULT" => "Y",
  ],
  "SHOW_DISCOUNT_PERCENT_VALUES" => [
    "NAME" => GetMessage("CPSL_SHOW_DISCOUNT_PERCENT_VALUES"),
    "TYPE" => "CHECKBOX",
    "MULTIPLE" => "N",
    "VALUE" => "Y",
    "DEFAULT" => "Y",
  ],
  "SHOW_DISCOUNT_PERCENT_NUMBER_OLD" => [
    "NAME" => GetMessage("CPSL_SHOW_DISCOUNT_PERCENT_NUMBER_OLD"),
    "TYPE" => "CHECKBOX",
    "MULTIPLE" => "N",
    "VALUE" => "Y",
    "DEFAULT" => "Y",
  ],
  "SHOW_DISCOUNT_PERCENT_NUMBER_NEW" => [
    "NAME" => GetMessage("CPSL_SHOW_DISCOUNT_PERCENT_NUMBER_NEW"),
    "TYPE" => "CHECKBOX",
    "MULTIPLE" => "N",
    "VALUE" => "Y",
    "DEFAULT" => "Y",
  ],
  "SHOW_DISCOUNT_PERCENT_NUMBER_OLD_ABS" => [
    "NAME" => GetMessage("CPSL_SHOW_DISCOUNT_PERCENT_NUMBER_OLD_ABS"),
    "TYPE" => "CHECKBOX",
    "MULTIPLE" => "N",
    "VALUE" => "Y",
    "DEFAULT" => "Y",
  ],
  "SHOW_DISCOUNT_PERCENT_NUMBER_NEW_ABS" => [
    "NAME" => GetMessage("CPSL_SHOW_DISCOUNT_PERCENT_NUMBER_NEW_ABS"),
    "TYPE" => "CHECKBOX",
    "MULTIPLE" => "N",
    "VALUE" => "Y",
    "DEFAULT" => "Y",
  ],
];
?>
