<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();
$arComponentParameters = array(
	"GROUPS" => array(
		"SETTINGS" => array(
			"NAME" => GetMessage("T_IBLOCK_DESC_SETTINGS"),
			"SORT" => 100,
		),
		"PRICE" => array(
			"NAME" => GetMessage("T_IBLOCK_DESC_PRICE"),
			"SORT" => 200,
		),
		"FILTER" => array(
			"NAME" => GetMessage("T_IBLOCK_DESC_FILTER"),
			"SORT" => 300,
		),
	),
	"PARAMETERS" => array(
		"IBLOCK_TYPE" => array(
			"PARENT" => "BASE",
			"NAME" => GetMessage("T_IBLOCK_DESC_TYPE"),
			"TYPE" => "LIST",
			"VALUES" => $arIBLockType,
			"REFRESH" => "Y",
		),
		"IBLOCK_ID" => array(
			"PARENT" => "BASE",
			"NAME" => GetMessage("T_IBLOCK_DESC_ID"),
			"TYPE" => "LIST",
			"VALUES" => $arIBlock,
			"REFRESH" => "Y",
			"ADDITIONAL_VALUES" => "Y",
		),
		"SECTION_ID" => array(
			"PARENT" => "BASE",
			"NAME" => GetMessage("T_IBLOCK_DESC_SECTION_ID"),
			"TYPE" => "STRING",
			"DEFAULT" => '={$_REQUEST["SECTION_ID"]}',
		),
		"SECTION_CODE" => array(
			"PARENT" => "BASE",
			"NAME" => GetMessage("T_IBLOCK_DESC_SECTION_CODE"),
			"TYPE" => "STRING",
			"DEFAULT" => '',
		),
		"SECTION_CODE_PATH" => array(
			"PARENT" => "BASE",
			"NAME" => GetMessage("T_IBLOCK_DESC_SECTION_CODE_PATH"),
			"TYPE" => "STRING",
			"DEFAULT" => '',
		),
		"ELEMENT_SORT_FIELD" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD"),
			"TYPE" => "LIST",
			"VALUES" => array(
				"sort" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_SORT"),
				"name" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_NAME"),
				"id" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_ID"),
				"date" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_DATE"),
				"price" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_PRICE"),
			),
			"DEFAULT" => "sort",
			"ADDITIONAL_VALUES" => "Y",
		),
		"ELEMENT_SORT_ORDER" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_ORDER"),
			"TYPE" => "LIST",
			"VALUES" => array(
				"asc" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_ORDER_ASC"),
				"desc" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_ORDER_DESC"),
			),
			"DEFAULT" => "asc",
		),
		"ELEMENT_SORT_FIELD2" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD2"),
			"TYPE" => "LIST",
			"VALUES" => array(
				"id" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_ID"),
				"name" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_NAME"),
				"sort" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_SORT"),
				"date" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_DATE"),
				"price" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_PRICE"),
			),
			"DEFAULT" => "id",
			"ADDITIONAL_VALUES" => "Y",
		),
		"ELEMENT_SORT_ORDER2" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_ORDER2"),
			"TYPE" => "LIST",
			"VALUES" => array(
				"asc" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_ORDER_ASC"),
				"desc" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_ORDER_DESC"),
			),
			"DEFAULT" => "desc",
		),
		"ELEMENT_COUNT" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_ELEMENT_COUNT"),
			"TYPE" => "STRING",
			"DEFAULT" => "20",
		),
		"LINE_ELEMENT_COUNT" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_LINE_ELEMENT_COUNT"),
			"TYPE" => "STRING",
			"DEFAULT" => "3",
		),
		"PROPERTY_CODE" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_PROPERTY_CODE"),
			"TYPE" => "LIST",
			"MULTIPLE" => "Y",
			"VALUES" => $arProperty_LNS,
			"ADDITIONAL_VALUES" => "Y",
		),
		"OFFERS_FIELD_CODE" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_OFFERS_FIELD_CODE"),
			"TYPE" => "LIST",
			"MULTIPLE" => "Y",
			"VALUES" => $arProperty_Off,
			"ADDITIONAL_VALUES" => "Y",
		),
		"OFFERS_PROPERTY_CODE" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_OFFERS_PROPERTY_CODE"),
			"TYPE" => "LIST",
			"MULTIPLE" => "Y",
			"VALUES" => $arProperty_Off,
			"ADDITIONAL_VALUES" => "Y",
		),
		"OFFERS_SORT_FIELD" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_OFFERS_SORT_FIELD"),
			"TYPE" => "LIST",
			"VALUES" => array(
				"id" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_ID"),
				"name" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_NAME"),
				"sort" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_SORT"),
				"price" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_PRICE"),
			),
			"DEFAULT" => "sort",
			"ADDITIONAL_VALUES" => "Y",
		),
		"OFFERS_SORT_ORDER" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_OFFERS_SORT_ORDER"),
			"TYPE" => "LIST",
			"VALUES" => array(
				"asc" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_ORDER_ASC"),
				"desc" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_ORDER_DESC"),
			),
			"DEFAULT" => "asc",
		),
		"OFFERS_SORT_FIELD2" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_OFFERS_SORT_FIELD2"),
			"TYPE" => "LIST",
			"VALUES" => array(
				"id" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_ID"),
				"name" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_NAME"),
				"sort" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_SORT"),
				"price" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_FIELD_PRICE"),
			),
			"DEFAULT" => "id",
			"ADDITIONAL_VALUES" => "Y",
		),
		"OFFERS_SORT_ORDER2" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_OFFERS_SORT_ORDER2"),
			"TYPE" => "LIST",
			"VALUES" => array(
				"asc" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_ORDER_ASC"),
				"desc" => GetMessage("T_IBLOCK_DESC_ELEMENT_SORT_ORDER_DESC"),
			),
			"DEFAULT" => "desc",
		),
		"OFFERS_LIMIT" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_OFFERS_LIMIT"),
			"TYPE" => "STRING",
			"DEFAULT" => "5",
		),
		"SECTION_URL" => array(
			"PARENT" => "URL_TEMPLATES",
			"NAME" => GetMessage("T_IBLOCK_DESC_SECTION_URL"),
			"TYPE" => "STRING",
			"DEFAULT" => "",
		),
		"CACHE_TYPE" => array(
			"PARENT" => "CACHE_SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_CACHE_TYPE"),
			"TYPE" => "LIST",
			"VALUES" => array(
				"A" => GetMessage("T_IBLOCK_DESC_CACHE_TYPE_AUTO"),
				"Y" => GetMessage("T_IBLOCK_DESC_CACHE_TYPE_YES"),
				"N" => GetMessage("T_IBLOCK_DESC_CACHE_TYPE_NO"),
			),
			"DEFAULT" => "A",
		),
		"CACHE_TIME" => array(
			"PARENT" => "CACHE_SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_CACHE_TIME"),
			"TYPE" => "STRING",
			"DEFAULT" => "36000000",
		),
		"CACHE_GROUPS" => array(
			"PARENT" => "CACHE_SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_CACHE_GROUPS"),
			"TYPE" => "CHECKBOX",
			"DEFAULT" => "Y",
		),
		"DISPLAY_COMPARE" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_DISPLAY_COMPARE"),
			"TYPE" => "CHECKBOX",
			"DEFAULT" => "N",
		),
		"COMPARE_PATH" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_COMPARE_PATH"),
			"TYPE" => "STRING",
			"DEFAULT" => "",
		),
		"PRICE_CODE" => array(
			"PARENT" => "PRICE",
			"NAME" => GetMessage("T_IBLOCK_DESC_PRICE_CODE"),
			"TYPE" => "LIST",
			"MULTIPLE" => "Y",
			"VALUES" => $arPrice,
		),
		"USE_PRICE_COUNT" => array(
			"PARENT" => "PRICE",
			"NAME" => GetMessage("T_IBLOCK_DESC_USE_PRICE_COUNT"),
			"TYPE" => "CHECKBOX",
			"DEFAULT" => "N",
		),
		"SHOW_PRICE_COUNT" => array(
			"PARENT" => "PRICE",
			"NAME" => GetMessage("T_IBLOCK_DESC_SHOW_PRICE_COUNT"),
			"TYPE" => "STRING",
			"DEFAULT" => "1",
		),
		"PRICE_VAT_INCLUDE" => array(
			"PARENT" => "PRICE",
			"NAME" => GetMessage("T_IBLOCK_DESC_PRICE_VAT_INCLUDE"),
			"TYPE" => "CHECKBOX",
			"DEFAULT" => "Y",
		),
		"CONVERT_CURRENCY" => array(
			"PARENT" => "PRICE",
			"NAME" => GetMessage("T_IBLOCK_DESC_CONVERT_CURRENCY"),
			"TYPE" => "CHECKBOX",
			"DEFAULT" => "N",
		),
		"CURRENCY_ID" => array(
			"PARENT" => "PRICE",
			"NAME" => GetMessage("T_IBLOCK_DESC_CURRENCY_ID"),
			"TYPE" => "LIST",
			"VALUES" => $arCurrency,
			"DEFAULT" => "USD",
		),
		"HIDE_NOT_AVAILABLE" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_HIDE_NOT_AVAILABLE"),
			"TYPE" => "CHECKBOX",
			"DEFAULT" => "N",
		),
		"HIDE_NOT_AVAILABLE_OFFERS" => array(
			"PARENT" => "SETTINGS",
			"NAME" => GetMessage("T_IBLOCK_DESC_HIDE_NOT_AVAILABLE_OFFERS"),
			"TYPE" => "CHECKBOX",
			"DEFAULT" => "N",
		),
		"USE_FILTER" => array(
			"PARENT" => "FILTER",
			"NAME" => GetMessage("T_IBLOCK_DESC_USE_FILTER"),
			"TYPE" => "CHECKBOX",
			"DEFAULT" => "N",
			"REFRESH" => "Y",
		),
	),
);
if($arCurrentValues["USE_FILTER"]=="Y")
{
	$arComponentParameters["PARAMETERS"]["FILTER_NAME"] = array(
		"PARENT" => "FILTER",
		"NAME" => GetMessage("T_IBLOCK_DESC_FILTER_NAME"),
		"TYPE" => "STRING",
		"DEFAULT" => "arrFilter",
	);
	$arComponentParameters["PARAMETERS"]["FILTER_FIELD_CODE"] = array(
		"PARENT" => "FILTER",
		"NAME" => GetMessage("T_IBLOCK_DESC_FILTER_FIELD_CODE"),
		"TYPE" => "LIST",
		"MULTIPLE" => "Y",
		"VALUES" => $arProperty_LNS,
		"ADDITIONAL_VALUES" => "Y",
	);
	$arComponentParameters["PARAMETERS"]["FILTER_PROPERTY_CODE"] = array(
		"PARENT" => "FILTER",
		"NAME" => GetMessage("T_IBLOCK_DESC_FILTER_PROPERTY_CODE"),
		"TYPE" => "LIST",
		"MULTIPLE" => "Y",
		"VALUES" => $arProperty_LNS,
		"ADDITIONAL_VALUES" => "Y",
	);
}
?> 